interface dataElements {
  team_id: number;
  team_long_name: string;
  team_short_name: string;
  total_goals: number;
}

const twoThousandEightSeason: Array<dataElements> = [
  {
    team_id: 10260,
    team_long_name: "Manchester United",
    team_short_name: "MUN",
    total_goals: 68,
  },
  {
    team_id: 10261,
    team_long_name: "Newcastle United",
    team_short_name: "NEW",
    total_goals: 40,
  },
  {
    team_id: 9825,
    team_long_name: "Arsenal",
    team_short_name: "ARS",
    total_goals: 68,
  },
  {
    team_id: 8659,
    team_long_name: "West Bromwich Albion",
    team_short_name: "WBA",
    total_goals: 36,
  },
  {
    team_id: 8472,
    team_long_name: "Sunderland",
    team_short_name: "SUN",
    total_goals: 34,
  },
  {
    team_id: 8650,
    team_long_name: "Liverpool",
    team_short_name: "LIV",
    total_goals: 77,
  },
  {
    team_id: 8654,
    team_long_name: "West Ham United",
    team_short_name: "WHU",
    total_goals: 42,
  },
  {
    team_id: 8528,
    team_long_name: "Wigan Athletic",
    team_short_name: "WIG",
    total_goals: 34,
  },
  {
    team_id: 10252,
    team_long_name: "Aston Villa",
    team_short_name: "AVL",
    total_goals: 54,
  },
  {
    team_id: 8456,
    team_long_name: "Manchester City",
    team_short_name: "MCI",
    total_goals: 58,
  },
  {
    team_id: 8668,
    team_long_name: "Everton",
    team_short_name: "EVE",
    total_goals: 55,
  },
  {
    team_id: 8655,
    team_long_name: "Blackburn Rovers",
    team_short_name: "BLB",
    total_goals: 40,
  },
  {
    team_id: 8549,
    team_long_name: "Middlesbrough",
    team_short_name: "MID",
    total_goals: 28,
  },
  {
    team_id: 8586,
    team_long_name: "Tottenham Hotspur",
    team_short_name: "TOT",
    total_goals: 45,
  },
  {
    team_id: 8559,
    team_long_name: "Bolton Wanderers",
    team_short_name: "BOL",
    total_goals: 41,
  },
  {
    team_id: 10194,
    team_long_name: "Stoke City",
    team_short_name: "STK",
    total_goals: 38,
  },
  {
    team_id: 8667,
    team_long_name: "Hull City",
    team_short_name: "HUL",
    total_goals: 39,
  },
  {
    team_id: 9879,
    team_long_name: "Fulham",
    team_short_name: "FUL",
    total_goals: 39,
  },
  {
    team_id: 8455,
    team_long_name: "Chelsea",
    team_short_name: "CHE",
    total_goals: 68,
  },
  {
    team_id: 8462,
    team_long_name: "Portsmouth",
    team_short_name: "POR",
    total_goals: 38,
  },
];

const twoThousandNineSeason: Array<dataElements> = [
  {
    team_id: 10260,
    team_long_name: "Manchester United",
    team_short_name: "MUN",
    total_goals: 86,
  },
  {
    team_id: 9825,
    team_long_name: "Arsenal",
    team_short_name: "ARS",
    total_goals: 83,
  },
  {
    team_id: 8472,
    team_long_name: "Sunderland",
    team_short_name: "SUN",
    total_goals: 48,
  },
  {
    team_id: 8650,
    team_long_name: "Liverpool",
    team_short_name: "LIV",
    total_goals: 61,
  },
  {
    team_id: 8654,
    team_long_name: "West Ham United",
    team_short_name: "WHU",
    total_goals: 47,
  },
  {
    team_id: 8528,
    team_long_name: "Wigan Athletic",
    team_short_name: "WIG",
    total_goals: 37,
  },
  {
    team_id: 10252,
    team_long_name: "Aston Villa",
    team_short_name: "AVL",
    total_goals: 52,
  },
  {
    team_id: 8456,
    team_long_name: "Manchester City",
    team_short_name: "MCI",
    total_goals: 73,
  },
  {
    team_id: 8668,
    team_long_name: "Everton",
    team_short_name: "EVE",
    total_goals: 60,
  },
  {
    team_id: 8655,
    team_long_name: "Blackburn Rovers",
    team_short_name: "BLB",
    total_goals: 41,
  },
  {
    team_id: 8586,
    team_long_name: "Tottenham Hotspur",
    team_short_name: "TOT",
    total_goals: 67,
  },
  {
    team_id: 8559,
    team_long_name: "Bolton Wanderers",
    team_short_name: "BOL",
    total_goals: 42,
  },
  {
    team_id: 10194,
    team_long_name: "Stoke City",
    team_short_name: "STK",
    total_goals: 34,
  },
  {
    team_id: 8667,
    team_long_name: "Hull City",
    team_short_name: "HUL",
    total_goals: 34,
  },
  {
    team_id: 9879,
    team_long_name: "Fulham",
    team_short_name: "FUL",
    total_goals: 39,
  },
  {
    team_id: 8455,
    team_long_name: "Chelsea",
    team_short_name: "CHE",
    total_goals: 103,
  },
  {
    team_id: 8462,
    team_long_name: "Portsmouth",
    team_short_name: "POR",
    total_goals: 34,
  },
  {
    team_id: 8658,
    team_long_name: "Birmingham City",
    team_short_name: "BIR",
    total_goals: 38,
  },
  {
    team_id: 8602,
    team_long_name: "Wolverhampton Wanderers",
    team_short_name: "WOL",
    total_goals: 32,
  },
  {
    team_id: 8191,
    team_long_name: "Burnley",
    team_short_name: "BUR",
    total_goals: 42,
  },
];

const twoThousandTenSeason: Array<dataElements> = [
  {
    team_id: 10260,
    team_long_name: "Manchester United",
    team_short_name: "MUN",
    total_goals: 78,
  },
  {
    team_id: 10261,
    team_long_name: "Newcastle United",
    team_short_name: "NEW",
    total_goals: 56,
  },
  {
    team_id: 9825,
    team_long_name: "Arsenal",
    team_short_name: "ARS",
    total_goals: 72,
  },
  {
    team_id: 8659,
    team_long_name: "West Bromwich Albion",
    team_short_name: "WBA",
    total_goals: 56,
  },
  {
    team_id: 8472,
    team_long_name: "Sunderland",
    team_short_name: "SUN",
    total_goals: 45,
  },
  {
    team_id: 8650,
    team_long_name: "Liverpool",
    team_short_name: "LIV",
    total_goals: 59,
  },
  {
    team_id: 8654,
    team_long_name: "West Ham United",
    team_short_name: "WHU",
    total_goals: 43,
  },
  {
    team_id: 8528,
    team_long_name: "Wigan Athletic",
    team_short_name: "WIG",
    total_goals: 40,
  },
  {
    team_id: 10252,
    team_long_name: "Aston Villa",
    team_short_name: "AVL",
    total_goals: 48,
  },
  {
    team_id: 8456,
    team_long_name: "Manchester City",
    team_short_name: "MCI",
    total_goals: 60,
  },
  {
    team_id: 8668,
    team_long_name: "Everton",
    team_short_name: "EVE",
    total_goals: 51,
  },
  {
    team_id: 8655,
    team_long_name: "Blackburn Rovers",
    team_short_name: "BLB",
    total_goals: 46,
  },
  {
    team_id: 8586,
    team_long_name: "Tottenham Hotspur",
    team_short_name: "TOT",
    total_goals: 55,
  },
  {
    team_id: 8559,
    team_long_name: "Bolton Wanderers",
    team_short_name: "BOL",
    total_goals: 52,
  },
  {
    team_id: 10194,
    team_long_name: "Stoke City",
    team_short_name: "STK",
    total_goals: 46,
  },
  {
    team_id: 9879,
    team_long_name: "Fulham",
    team_short_name: "FUL",
    total_goals: 49,
  },
  {
    team_id: 8455,
    team_long_name: "Chelsea",
    team_short_name: "CHE",
    total_goals: 69,
  },
  {
    team_id: 8658,
    team_long_name: "Birmingham City",
    team_short_name: "BIR",
    total_goals: 37,
  },
  {
    team_id: 8602,
    team_long_name: "Wolverhampton Wanderers",
    team_short_name: "WOL",
    total_goals: 46,
  },
  {
    team_id: 8483,
    team_long_name: "Blackpool",
    team_short_name: "BLA",
    total_goals: 55,
  },
];

const twoThousandEleven: Array<dataElements> = [
  {
    team_id: 10260,
    team_long_name: "Manchester United",
    team_short_name: "MUN",
    total_goals: 89,
  },
  {
    team_id: 10261,
    team_long_name: "Newcastle United",
    team_short_name: "NEW",
    total_goals: 56,
  },
  {
    team_id: 9825,
    team_long_name: "Arsenal",
    team_short_name: "ARS",
    total_goals: 74,
  },
  {
    team_id: 8659,
    team_long_name: "West Bromwich Albion",
    team_short_name: "WBA",
    total_goals: 45,
  },
  {
    team_id: 8472,
    team_long_name: "Sunderland",
    team_short_name: "SUN",
    total_goals: 45,
  },
  {
    team_id: 8650,
    team_long_name: "Liverpool",
    team_short_name: "LIV",
    total_goals: 47,
  },
  {
    team_id: 8528,
    team_long_name: "Wigan Athletic",
    team_short_name: "WIG",
    total_goals: 42,
  },
  {
    team_id: 10252,
    team_long_name: "Aston Villa",
    team_short_name: "AVL",
    total_goals: 37,
  },
  {
    team_id: 8456,
    team_long_name: "Manchester City",
    team_short_name: "MCI",
    total_goals: 93,
  },
  {
    team_id: 8668,
    team_long_name: "Everton",
    team_short_name: "EVE",
    total_goals: 50,
  },
  {
    team_id: 8655,
    team_long_name: "Blackburn Rovers",
    team_short_name: "BLB",
    total_goals: 48,
  },
  {
    team_id: 8586,
    team_long_name: "Tottenham Hotspur",
    team_short_name: "TOT",
    total_goals: 66,
  },
  {
    team_id: 8559,
    team_long_name: "Bolton Wanderers",
    team_short_name: "BOL",
    total_goals: 46,
  },
  {
    team_id: 10194,
    team_long_name: "Stoke City",
    team_short_name: "STK",
    total_goals: 36,
  },
  {
    team_id: 9879,
    team_long_name: "Fulham",
    team_short_name: "FUL",
    total_goals: 48,
  },
  {
    team_id: 8455,
    team_long_name: "Chelsea",
    team_short_name: "CHE",
    total_goals: 65,
  },
  {
    team_id: 8602,
    team_long_name: "Wolverhampton Wanderers",
    team_short_name: "WOL",
    total_goals: 40,
  },
  {
    team_id: 10003,
    team_long_name: "Swansea City",
    team_short_name: "SWA",
    total_goals: 44,
  },
  {
    team_id: 10172,
    team_long_name: "Queens Park Rangers",
    team_short_name: "QPR",
    total_goals: 43,
  },
  {
    team_id: 9850,
    team_long_name: "Norwich City",
    team_short_name: "NOR",
    total_goals: 52,
  },
];

const twoThousandTwelve: Array<dataElements> = [
  {
    team_id: 10260,
    team_long_name: "Manchester United",
    team_short_name: "MUN",
    total_goals: 86,
  },
  {
    team_id: 10261,
    team_long_name: "Newcastle United",
    team_short_name: "NEW",
    total_goals: 45,
  },
  {
    team_id: 9825,
    team_long_name: "Arsenal",
    team_short_name: "ARS",
    total_goals: 72,
  },
  {
    team_id: 8659,
    team_long_name: "West Bromwich Albion",
    team_short_name: "WBA",
    total_goals: 53,
  },
  {
    team_id: 8472,
    team_long_name: "Sunderland",
    team_short_name: "SUN",
    total_goals: 41,
  },
  {
    team_id: 8650,
    team_long_name: "Liverpool",
    team_short_name: "LIV",
    total_goals: 71,
  },
  {
    team_id: 8654,
    team_long_name: "West Ham United",
    team_short_name: "WHU",
    total_goals: 45,
  },
  {
    team_id: 8528,
    team_long_name: "Wigan Athletic",
    team_short_name: "WIG",
    total_goals: 47,
  },
  {
    team_id: 10252,
    team_long_name: "Aston Villa",
    team_short_name: "AVL",
    total_goals: 47,
  },
  {
    team_id: 8456,
    team_long_name: "Manchester City",
    team_short_name: "MCI",
    total_goals: 66,
  },
  {
    team_id: 8668,
    team_long_name: "Everton",
    team_short_name: "EVE",
    total_goals: 55,
  },
  {
    team_id: 8586,
    team_long_name: "Tottenham Hotspur",
    team_short_name: "TOT",
    total_goals: 66,
  },
  {
    team_id: 10194,
    team_long_name: "Stoke City",
    team_short_name: "STK",
    total_goals: 34,
  },
  {
    team_id: 9879,
    team_long_name: "Fulham",
    team_short_name: "FUL",
    total_goals: 50,
  },
  {
    team_id: 8455,
    team_long_name: "Chelsea",
    team_short_name: "CHE",
    total_goals: 75,
  },
  {
    team_id: 10003,
    team_long_name: "Swansea City",
    team_short_name: "SWA",
    total_goals: 47,
  },
  {
    team_id: 10172,
    team_long_name: "Queens Park Rangers",
    team_short_name: "QPR",
    total_goals: 30,
  },
  {
    team_id: 9850,
    team_long_name: "Norwich City",
    team_short_name: "NOR",
    total_goals: 41,
  },
  {
    team_id: 8466,
    team_long_name: "Southampton",
    team_short_name: "SOU",
    total_goals: 49,
  },
  {
    team_id: 9798,
    team_long_name: "Reading",
    team_short_name: "REA",
    total_goals: 43,
  },
];

const twoThousandThirteen: Array<dataElements> = [
  {
    team_id: 10260,
    team_long_name: "Manchester United",
    team_short_name: "MUN",
    total_goals: 64,
  },
  {
    team_id: 10261,
    team_long_name: "Newcastle United",
    team_short_name: "NEW",
    total_goals: 43,
  },
  {
    team_id: 9825,
    team_long_name: "Arsenal",
    team_short_name: "ARS",
    total_goals: 68,
  },
  {
    team_id: 8659,
    team_long_name: "West Bromwich Albion",
    team_short_name: "WBA",
    total_goals: 43,
  },
  {
    team_id: 8472,
    team_long_name: "Sunderland",
    team_short_name: "SUN",
    total_goals: 41,
  },
  {
    team_id: 8650,
    team_long_name: "Liverpool",
    team_short_name: "LIV",
    total_goals: 101,
  },
  {
    team_id: 8654,
    team_long_name: "West Ham United",
    team_short_name: "WHU",
    total_goals: 40,
  },
  {
    team_id: 10252,
    team_long_name: "Aston Villa",
    team_short_name: "AVL",
    total_goals: 39,
  },
  {
    team_id: 8456,
    team_long_name: "Manchester City",
    team_short_name: "MCI",
    total_goals: 102,
  },
  {
    team_id: 8668,
    team_long_name: "Everton",
    team_short_name: "EVE",
    total_goals: 61,
  },
  {
    team_id: 8586,
    team_long_name: "Tottenham Hotspur",
    team_short_name: "TOT",
    total_goals: 55,
  },
  {
    team_id: 10194,
    team_long_name: "Stoke City",
    team_short_name: "STK",
    total_goals: 45,
  },
  {
    team_id: 8667,
    team_long_name: "Hull City",
    team_short_name: "HUL",
    total_goals: 38,
  },
  {
    team_id: 9879,
    team_long_name: "Fulham",
    team_short_name: "FUL",
    total_goals: 40,
  },
  {
    team_id: 8455,
    team_long_name: "Chelsea",
    team_short_name: "CHE",
    total_goals: 71,
  },
  {
    team_id: 10003,
    team_long_name: "Swansea City",
    team_short_name: "SWA",
    total_goals: 54,
  },
  {
    team_id: 9850,
    team_long_name: "Norwich City",
    team_short_name: "NOR",
    total_goals: 28,
  },
  {
    team_id: 8466,
    team_long_name: "Southampton",
    team_short_name: "SOU",
    total_goals: 54,
  },
  {
    team_id: 9826,
    team_long_name: "Crystal Palace",
    team_short_name: "CRY",
    total_goals: 33,
  },
  {
    team_id: 8344,
    team_long_name: "Cardiff City",
    team_short_name: "CAR",
    total_goals: 32,
  },
];

const twoThousandFourteen: Array<dataElements> = [
  {
    team_id: 10260,
    team_long_name: "Manchester United",
    team_short_name: "MUN",
    total_goals: 62,
  },
  {
    team_id: 10261,
    team_long_name: "Newcastle United",
    team_short_name: "NEW",
    total_goals: 40,
  },
  {
    team_id: 9825,
    team_long_name: "Arsenal",
    team_short_name: "ARS",
    total_goals: 71,
  },
  {
    team_id: 8659,
    team_long_name: "West Bromwich Albion",
    team_short_name: "WBA",
    total_goals: 38,
  },
  {
    team_id: 8472,
    team_long_name: "Sunderland",
    team_short_name: "SUN",
    total_goals: 31,
  },
  {
    team_id: 8650,
    team_long_name: "Liverpool",
    team_short_name: "LIV",
    total_goals: 52,
  },
  {
    team_id: 8654,
    team_long_name: "West Ham United",
    team_short_name: "WHU",
    total_goals: 44,
  },
  {
    team_id: 10252,
    team_long_name: "Aston Villa",
    team_short_name: "AVL",
    total_goals: 31,
  },
  {
    team_id: 8456,
    team_long_name: "Manchester City",
    team_short_name: "MCI",
    total_goals: 83,
  },
  {
    team_id: 8668,
    team_long_name: "Everton",
    team_short_name: "EVE",
    total_goals: 48,
  },
  {
    team_id: 8586,
    team_long_name: "Tottenham Hotspur",
    team_short_name: "TOT",
    total_goals: 58,
  },
  {
    team_id: 10194,
    team_long_name: "Stoke City",
    team_short_name: "STK",
    total_goals: 48,
  },
  {
    team_id: 8667,
    team_long_name: "Hull City",
    team_short_name: "HUL",
    total_goals: 33,
  },
  {
    team_id: 8455,
    team_long_name: "Chelsea",
    team_short_name: "CHE",
    total_goals: 73,
  },
  {
    team_id: 8191,
    team_long_name: "Burnley",
    team_short_name: "BUR",
    total_goals: 28,
  },
  {
    team_id: 10003,
    team_long_name: "Swansea City",
    team_short_name: "SWA",
    total_goals: 46,
  },
  {
    team_id: 10172,
    team_long_name: "Queens Park Rangers",
    team_short_name: "QPR",
    total_goals: 42,
  },
  {
    team_id: 8466,
    team_long_name: "Southampton",
    team_short_name: "SOU",
    total_goals: 54,
  },
  {
    team_id: 9826,
    team_long_name: "Crystal Palace",
    team_short_name: "CRY",
    total_goals: 47,
  },
  {
    team_id: 8197,
    team_long_name: "Leicester City",
    team_short_name: "LEI",
    total_goals: 46,
  },
];

const twoThousandFifteen: Array<dataElements> = [
  {
    team_id: 10260,
    team_long_name: "Manchester United",
    team_short_name: "MUN",
    total_goals: 49,
  },
  {
    team_id: 10261,
    team_long_name: "Newcastle United",
    team_short_name: "NEW",
    total_goals: 44,
  },
  {
    team_id: 9825,
    team_long_name: "Arsenal",
    team_short_name: "ARS",
    total_goals: 65,
  },
  {
    team_id: 8659,
    team_long_name: "West Bromwich Albion",
    team_short_name: "WBA",
    total_goals: 34,
  },
  {
    team_id: 8472,
    team_long_name: "Sunderland",
    team_short_name: "SUN",
    total_goals: 48,
  },
  {
    team_id: 8650,
    team_long_name: "Liverpool",
    team_short_name: "LIV",
    total_goals: 63,
  },
  {
    team_id: 8654,
    team_long_name: "West Ham United",
    team_short_name: "WHU",
    total_goals: 65,
  },
  {
    team_id: 10252,
    team_long_name: "Aston Villa",
    team_short_name: "AVL",
    total_goals: 27,
  },
  {
    team_id: 8456,
    team_long_name: "Manchester City",
    team_short_name: "MCI",
    total_goals: 71,
  },
  {
    team_id: 8668,
    team_long_name: "Everton",
    team_short_name: "EVE",
    total_goals: 59,
  },
  {
    team_id: 8586,
    team_long_name: "Tottenham Hotspur",
    team_short_name: "TOT",
    total_goals: 69,
  },
  {
    team_id: 10194,
    team_long_name: "Stoke City",
    team_short_name: "STK",
    total_goals: 41,
  },
  {
    team_id: 8455,
    team_long_name: "Chelsea",
    team_short_name: "CHE",
    total_goals: 59,
  },
  {
    team_id: 10003,
    team_long_name: "Swansea City",
    team_short_name: "SWA",
    total_goals: 42,
  },
  {
    team_id: 9850,
    team_long_name: "Norwich City",
    team_short_name: "NOR",
    total_goals: 39,
  },
  {
    team_id: 8466,
    team_long_name: "Southampton",
    team_short_name: "SOU",
    total_goals: 59,
  },
  {
    team_id: 9826,
    team_long_name: "Crystal Palace",
    team_short_name: "CRY",
    total_goals: 39,
  },
  {
    team_id: 8197,
    team_long_name: "Leicester City",
    team_short_name: "LEI",
    total_goals: 68,
  },
  {
    team_id: 8678,
    team_long_name: "Bournemouth",
    team_short_name: "BOU",
    total_goals: 45,
  },
  {
    team_id: 9817,
    team_long_name: "Watford",
    team_short_name: "WAT",
    total_goals: 40,
  },
];

export {
  twoThousandEightSeason,
  twoThousandNineSeason,
  twoThousandTenSeason,
  twoThousandEleven,
  twoThousandTwelve,
  twoThousandThirteen,
  twoThousandFourteen,
  twoThousandFifteen,
};
